# Copyright 2017, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      SL_CMAKE_VS: 12 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      SL_CMAKE_VS: 15 2017

clone_folder: c:\projects\staticlib_pion

install:
  - cd ..
  - git clone https://github.com/staticlibs/tools_windows_pkgconfig.git
  - git clone https://github.com/staticlibs/tools_windows_perl520.git
  - git clone https://github.com/staticlibs/tools_windows_nasm.git
  - set PATH=%PATH%;c:\projects\tools_windows_pkgconfig\bin;c:\projects\tools_windows_perl520\perl\bin;c:\projects\tools_windows_nasm
  - git clone https://github.com/staticlibs/cmake.git
  - git clone https://github.com/staticlibs/external_asio.git
  - git clone https://github.com/staticlibs/lookaside_asio.git
  - git clone https://github.com/staticlibs/external_openssl.git
  - git clone https://github.com/staticlibs/lookaside_openssl.git
  - git clone https://github.com/staticlibs/staticlib_config.git
  - git clone https://github.com/staticlibs/staticlib_support.git
  - git clone https://github.com/staticlibs/staticlib_io.git
  - git clone https://github.com/staticlibs/staticlib_utils.git
  - mkdir test
  - robocopy staticlib_pion\test\certificates test\certificates /e /ndl /njh /njs /nc /ns /np || true

build: off

build_script:
  - mkdir build-standalone
  - cd build-standalone
  - cmake ../staticlib_pion
  - cmake --build .
  - cd ..
  - mkdir build_i386
  - cd build_i386
  - cmake ../staticlib_pion/test
        -G "Visual Studio %SL_CMAKE_VS%"
        -DSTATICLIB_TOOLCHAIN=windows_i386_msvc
        -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ctest
  - cd ..
  - mkdir build_amd64
  - cd build_amd64
  - cmake ../staticlib_pion/test
        -G "Visual Studio %SL_CMAKE_VS% Win64"
        -DSTATICLIB_TOOLCHAIN=windows_amd64_msvc
        -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ctest
